name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
		
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 19
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: jamesives/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out